<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.util_services.env' shared service.

return $this->services['klaviyops.util_services.env'] = new \KlaviyoPs\Classes\UtilServices\EnvService(${($_ = isset($this->services['klaviyops.module']) ? $this->services['klaviyops.module'] : $this->load('getKlaviyops_ModuleService.php')) && false ?: '_'});
