<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.klaviyo_service.coupon_generator' shared service.

return $this->services['klaviyops.klaviyo_service.coupon_generator'] = new \KlaviyoPs\Classes\KlaviyoServices\CouponGeneratorService(${($_ = isset($this->services['klaviyops.prestashop_services.cart_rule']) ? $this->services['klaviyops.prestashop_services.cart_rule'] : ($this->services['klaviyops.prestashop_services.cart_rule'] = new \KlaviyoPs\Classes\PrestashopServices\CartRuleService())) && false ?: '_'});
