<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.prestashop_services.order' shared service.

return $this->services['klaviyops.prestashop_services.order'] = new \KlaviyoPs\Classes\PrestashopServices\OrderService(${($_ = isset($this->services['klaviyops.prestashop_services.context']) ? $this->services['klaviyops.prestashop_services.context'] : $this->load('getKlaviyops_PrestashopServices_ContextService.php')) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.product']) ? $this->services['klaviyops.prestashop_services.product'] : ($this->services['klaviyops.prestashop_services.product'] = new \KlaviyoPs\Classes\PrestashopServices\ProductService())) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.customer']) ? $this->services['klaviyops.prestashop_services.customer'] : $this->load('getKlaviyops_PrestashopServices_CustomerService.php')) && false ?: '_'});
