services:
  memcache:
    container_name: memcached
    image: memcached
    user: 1000:1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - prestanet
      
  prestashop:
    image: alexander0077/prestashop:latest
    user: root
    ports:
      - 18867:443
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PS_DEV_MODE: 0
      PS_INSTALL_AUTO: 1
      DB_SERVER: db
      DB_USER: root
      DB_NAME: BE_188672
      DB_PASSWD: student
      PS_COUNTRY: pl
      PS_LANGUAGE: pl
    networks:
      - prestanet
      - admin-mysql_default
    entrypoint: /initialize.sh
    
networks:
  prestanet:
  admin-mysql_default:
    external: true
