services:
  prestashop:
    image: alexander0077/biznes:latest
    user: root
    ports:
      - 18867:443
    depends_on:
      - memcached
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - BE_188672:/var/www/html
    networks:
      - admin-mysql_default
    entrypoint: /init_script.sh
  memcached:
    image: memcached:1.6.10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - admin-mysql_default
networks:
  admin-mysql_default:
    external: true
volumes:
  BE_188672: