<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3q59qkb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3q59qkb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3q59qkb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3q59qkb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3q59qkb\appDevDebugProjectContainer([
    'container.build_hash' => '3q59qkb',
    'container.build_id' => 'c5c12481',
    'container.build_time' => 1700936691,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3q59qkb');
