<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzbcilk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzbcilk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVzbcilk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVzbcilk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVzbcilk\appDevDebugProjectContainer([
    'container.build_hash' => 'Vzbcilk',
    'container.build_id' => 'e94ecddc',
    'container.build_time' => 1701186485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzbcilk');
