<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAzxo1ga\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAzxo1ga/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAzxo1ga.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAzxo1ga\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAzxo1ga\appProdProjectContainer([
    'container.build_hash' => 'Azxo1ga',
    'container.build_id' => '4490a021',
    'container.build_time' => 1697141030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAzxo1ga');
