<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ4advau\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ4advau/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQ4advau.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQ4advau\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQ4advau\appProdProjectContainer([
    'container.build_hash' => 'Q4advau',
    'container.build_id' => 'aadcd3b4',
    'container.build_time' => 1697271107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ4advau');
