<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.prestashop_services.context' shared service.

return $this->services['klaviyops.prestashop_services.context'] = new \KlaviyoPs\Classes\PrestashopServices\ContextService(${($_ = isset($this->services['klaviyops.prestashop_components.context']) ? $this->services['klaviyops.prestashop_components.context'] : $this->load('getKlaviyops_PrestashopComponents_ContextService.php')) && false ?: '_'});
